In [22]:
import numpy as np

class State:
    def __init__(self, origin, destin, heuristic, board):
        self.origin = origin
        self.destin = destin
        self.heuristic = heuristic
        self.board = board
    def __init__(self,board):
        self.origin = None
        self.destin = None
        self.heuristic = 0
        self.board = board

def initialize_board():
    board = np.zeros((8,8))
    board[3][3], board[4][4] = 1,1
    board[4][3], board[3][4] = -1,-1
    return board

print(initialize_board())

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [8]:
def alpha_beta_search(state, player):
    if player == "max":
        return max_value(state, np.Inf, np.NINF)
    return min_value(state, np.Inf, np.NINF)

def terminal_test(state):
    return False

def utility(state):
    return _

def list_actions(state, player):
    token = 1
    if player == "min" : token = -1
    enemy_indexes = np.where(state == -token)
    enemy_coordinates= list(zip(enemy_indexes[0], enemy_indexes[1]))
    return enemy_coordinates

def min_value(state, alpha, beta):
    if(terminal_test(state)): return utility(state)
    v = np.Inf
    for action in Actions(State):
        v = min(v, max_value(state, alpha, beta))
        if(v<=alpha): return v
        beta = min(beta, v)
    return v

def max_value(state, alpha, beta):
    if(terminal_test(state)): return utility(state)
    v = np.NINF
    for action in Actions(State):
        v = max(v, min_value(state, alpha, beta))
        if(v>=beta): return v
        alpha = max(alpha, v)
    return v

In [28]:

asd = {
    0:[1,2],
    1:[5,3]
}
asd2 = [5,4]
asd3 = []
asd[asd2.index(max(asd2))]

[1, 2]

In [34]:
print(np.NINF)
np.Inf
print(np.NINF>0)

-inf
False


In [9]:
board = np.array(initialize_board())
indexes = np.where(board > 0)
indexes

(array([3, 4], dtype=int64), array([3, 4], dtype=int64))

In [10]:
listasd = list_actions(board, "max")
print(listasd)

[(3, 4), (4, 3)]


In [44]:
import copy

def can_move_up(piece, board, player_piece):# 1 -> y  0 -> x
    if piece[1] == 0: return False
    if board[piece[0]][piece[1]-1] == player_piece: return False
    if board[piece[0]][piece[1]-1] == player_piece*-1: return "Enemy"
    return "Empty" #enemy found?
def can_move_down(piece, board, player_piece):
    if piece[1] == 7: return False
    if board[piece[0]][piece[1]+1] == player_piece: return False
    if board[piece[0]][piece[1]+1] == player_piece*-1: return "Enemy"
    return "Empty"
def can_move_left(piece, board, player_piece):
    if piece[0] == 0: return False
    if board[piece[0]-1][piece[1]] == player_piece: return False
    if board[piece[0]-1][piece[1]] == player_piece*-1: return "Enemy"
    return "Empty"
def can_move_right(piece, board, player_piece):
    if piece[0] ==7 : return False
    if board[piece[0]+1][piece[1]] == player_piece: return False
    print(piece, (piece[0]+1, piece[1]), board[piece[0]+1][piece[1]], board[piece[0]][piece[1]])
    print(board)
    if board[piece[0]+1][piece[1]] == player_piece*-1: 
        print("Enemy found")
        return "Enemy"
    return "Empty"

def move_up_left(piece, board, player_piece,utility=0, enemy_positions=[]):# 1 -> y  0 -> x
    next_position = (piece[0]-1,piece[1]-1)
    if not can_move_up(piece, board, player_piece) or not can_move_left(piece, board, player_piece) : return False,_,_,0
    if board[next_position[0]][next_position[1]] == 0 and utility>0: #Found empty space and can at least take one enemy
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_up_left(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))#enemy found
def move_up_right(piece, board, player_piece,utility=0, enemy_positions=[]):
    next_position = (piece[0]+1,piece[1]-1)
    if not can_move_up(piece, board, player_piece) or not can_move_right(piece, board, player_piece) : return False,_,_,0
    if board[next_position[0]][next_position[1]] == 0 and utility>0: 
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_up_right(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))#enemy found
def move_down_left(piece, board, player_piece,utility=0, enemy_positions=[]):
    next_position = (piece[0]-1,piece[1]+1)
    if not can_move_down(piece, board, player_piece) or not can_move_left(piece, board, player_piece) : return False,_,_,0
    if board[next_position[0]][next_position[1]] == 0 and utility>0: 
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_down_left(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))#enemy found
def move_down_right(piece, board, player_piece,utility=0, enemy_positions=[]):
    next_position = (piece[0]+1,piece[1]+1)
    if not can_move_down(piece, board, player_piece) or not can_move_right(piece, board, player_piece) : return False,_,_,0
    if board[next_position[0]][next_position[1]] == 0 and utility>0: 
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_down_right(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))#enemy found

def move_up(piece, board, player_piece,utility=0, enemy_positions=[]):
    next_position = (piece[0],piece[1]-1)
    up_state = can_move_up(piece, board, player_piece)
    if not up_state: return False,_,_,0
    if up_state == "Empty" and utility>0:
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_up(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))
def move_down(piece, board, player_piece,utility=0, enemy_positions=[]):
    next_position = (piece[0],piece[1]+1)
    down_state = can_move_down(piece, board, player_piece)
    if not down_state: return False,_,_,0
    if down_state == "Empty" and utility>0:
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_down(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))
def move_right(piece, board, player_piece,utility=0, enemy_positions=[]):
    next_position = (piece[0]+1,piece[1])
    right_state = can_move_right(piece, board, player_piece)
    if not right_state: return False,_,_,0
    if right_state == "Empty" and utility>0:
        print("Hello")
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_right(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))
def move_left(piece, board, player_piece,utility=0, enemy_positions=[]):
    next_position = (piece[0]-1,piece[1])
    left_state = can_move_left(piece, board, player_piece)
    if not left_state: return False,_,_,0
    if left_state == "Empty" and utility>0:
        return True,(next_position),enemy_positions,utility
    else:
        return False,_,_,0
    return move_left(next_position, board, player_piece, utility+1,enemy_positions.append(next_position))

def moves(state, player):
    possible_moves = [can_move_up,can_move_down,can_move_left,can_move_right,can_move_up_left,can_move_up_right,can_move_down_left,can_move_down_right]
    moves_checker = []
    player_pieces = list_actions(board, player)
    player_piece = 1
    new_states = []
    if player == "min": player_piece = -1
    for piece in player_pieces:
        print(piece, player_piece)
        can_move, move_position, enemies_taken_list, utility = move_up(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
        can_move, move_position, enemies_taken_list, utility = move_down(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
        can_move, move_position, enemies_taken_list, utility = move_right(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
        can_move, move_position, enemies_taken_list, utility = move_left(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
        
        can_move, move_position, enemies_taken_list, utility = move_up_right(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
        can_move, move_position, enemies_taken_list, utility = move_up_left(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
        can_move, move_position, enemies_taken_list, utility = move_down_right(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
        can_move, move_position, enemies_taken_list, utility = move_down_left(piece, state.board, player_piece)
        if can_move: new_states.append(State(piece, move_position, utility, board))
    return new_states

the_state = State(board)
new_states = moves(the_state, "max")
print(new_states)

(3, 4) 1
(4, 3) 1
(4, 3) (5, 3) 0.0 -1.0
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
(4, 3) (5, 3) 0.0 -1.0
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[]


In [33]:
strin = False
if not strin:
    print(":D")
if strin == "ASD":
    print("XD")

:D


In [39]:
print(-1 == 1.0*-1)

True
