In [2]:
import numpy as np

class State:
    def __init__(self):
        self.origin = None
        self.destin = None
        self.heuristic = 0
        self.enemies_taken = None
        self.board = none

def initialize_board():
    board = np.zeros((8,8))
    board[3][3], board[4][4] = 1,1
    board[4][3], board[3][4] = -1,-1
    return board

print(initialize_board())

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [3]:
def alpha_beta_search(state, player):
    if player == "max":
        return max_value(state, np.Inf, np.NINF)
    return min_value(state, np.Inf, np.NINF)

def terminal_test(state):
    return False

def utility(state):
    return _

def list_actions(state, player):
    token = 1
    if player == "min" : token = -1
    enemy_indexes = np.where(state == -token)
    enemy_coordinates= list(zip(enemy_indexes[0], enemy_indexes[1]))
    return enemy_coordinates

def min_value(state, alpha, beta):
    if(terminal_test(state)): return utility(state)
    v = np.Inf
    for action in Actions(State):
        v = min(v, max_value(state, alpha, beta))
        if(v<=alpha): return v
        beta = min(beta, v)
    return v

def max_value(state, alpha, beta):
    if(terminal_test(state)): return utility(state)
    v = np.Inf
    for action in Actions(State):
        v = max(v, min_value(state, alpha, beta))
        if(v>=beta): return v
        alpha = max(alpha, v)
    return v

In [28]:

asd = {
    0:[1,2],
    1:[5,3]
}
asd2 = [5,4]
asd3 = []
asd[asd2.index(max(asd2))]

[1, 2]

In [34]:
print(np.NINF)
np.Inf
print(np.NINF>0)

-inf
False


In [5]:
board = np.array(initialize_board())
indexes = np.where(board > 0)
indexes

(array([3, 4], dtype=int64), array([3, 4], dtype=int64))

In [4]:
listOfCoordinates= list_actions(board, "max")
print(listOfCoordinates)
for cord in listOfCoordinates:
    print(cord)
    
    

NameError: name 'indexes' is not defined

In [10]:
listasd = list_actions(board, "max")
print(listasd)

[(3, 4), (4, 3)]


In [ ]:
def moves(state, player):
    possible_moves = []
    player_moves = list_actions(player)
    for move in player_moves:
        if move == (0,0):
            
    return possible_moves